# -- Theme Options --
colorScheme = "blowfish"
defaultAppearance = "dark" 
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
replyByEmail = false
mainSections = ["docs", "posts"]

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false

# Estilos de fondo recuperados
defaultBackgroundImage = "img/wald.jpg" 
defaultFeaturedImage = "img/cover.png" 
defaultSocialImage = "/android-chrome-512x512.png" 

[header]
  layout = "fixed" 

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "custom" 
  # ESTO RECUPERA TUS PUBLICACIONES (No lo pongas en false)
  showRecent = true 
  showRecentItems = 10
  # ESTO ELIMINA EL BANNER AZUL DE "SWITCH CONFIG"
  showMoreLink = false 
  cardView = false
  layoutBackgroundBlur = true 

[article]
  showAuthor = true
  showHero = false
  heroStyle = "basic" 
  showTableOfContents = true

[list]
  # CONFIGURACIÓN PARA POSTS PEQUEÑOS (MODO LISTA)
  showHero = false            # Elimina el error "home.html not found" del terminal
  heroStyle = "basic"
  
  showCards = false           # Quita los cuadros gigantes
  cardView = false            # Fuerza la vista de lista horizontal
  compact = true              # ESTA ES LA CLAVE para el tamaño pequeño
  
  showSummary = true          # Texto a la derecha de la imagen
  showViews = true 
  showLikes = true 
  showBreadcrumbs = false
  groupByYear = false
  constrainItemsWidth = true

[taxonomy]
  cardView = false

[term]
  cardView = false 

[buymeacoffee]
  identifier = "oscarchavezgallardo"
  globalWidget = true