# -- Theme Options --
colorScheme = "blowfish"
defaultAppearance = "dark" 
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
replyByEmail = false
mainSections = ["docs", "posts"]

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false

# Estilos de fondo
defaultBackgroundImage = "img/wald.jpg" 
defaultFeaturedImage = "img/cover.png" 
defaultSocialImage = "/android-chrome-512x512.png" 

[header]
  layout = "fixed" 

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "custom" 
  showRecent = true 
  showRecentItems = 10
  showMoreLink = true  # Muestra el botón de "Ver más" al final
  cardView = false     # Desactiva las tarjetas en la página de inicio
  layoutBackgroundBlur = true 

[article]
  showAuthor = true
  showHero = false
  heroStyle = "basic" 
  showTableOfContents = true

[list]
  # CONFIGURACIÓN PARA EL DISEÑO COMPACTO (IMAGEN A LA IZQUIERDA)
  showHero = false            
  heroStyle = "basic"
  showSummary = true          # Muestra el texto a la derecha de la imagen
  showViews = true 
  showLikes = true 
  showCards = false           # IMPORTANTE: Desactiva los cuadros gigantes
  cardView = false            # Asegura que la lista sea horizontal
  compact = true              # ESTA ES LA CLAVE: Activa el modo compacto de Blowfish
  showBreadcrumbs = false
  groupByYear = false
  constrainItemsWidth = true

[taxonomy]
  cardView = false

[term]
  cardView = false 

[buymeacoffee]
  identifier = "oscarchavezgallardo"
  globalWidget = true